# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_italiani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comune',
            name='label',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=350, null=True),
        ),
    ]
